// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notesnook.API.Data;

#nullable disable

namespace Notesnook.API.Data.Migrations
{
    [DbContext(typeof(NotesnookDbContext))]
    partial class NotesnookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Notesnook.API.Models.Announcement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("AppVersion")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "appVersion");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "body");

                    b.Property<string>("CallToActions")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "callToActions");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "isActive");

                    b.Property<string>("Platforms")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "platforms");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<string>("UserIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserTypes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "userTypes");

                    b.HasKey("Id");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("Notesnook.API.Models.DevicePendingId", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bucket")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "DeviceId", "Bucket", "ItemId", "Type");

                    b.HasIndex("UserId", "DeviceId", "Bucket");

                    b.ToTable("device_pending_ids", (string)null);
                });

            modelBuilder.Entity("Notesnook.API.Models.InboxApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("DateCreated")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "dateCreated");

                    b.Property<long>("ExpiryDate")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "expiryDate");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "key");

                    b.Property<long>("LastUsedAt")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "lastUsedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("inbox_api_keys", (string)null);
                });

            modelBuilder.Entity("Notesnook.API.Models.InboxSyncItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "alg");

                    b.Property<string>("Cipher")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cipher");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.Property<double>("Version")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "v");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId");

                    b.ToTable("inbox_sync_items", (string)null);
                });

            modelBuilder.Entity("Notesnook.API.Models.Monograph", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CompressedContent")
                        .HasColumnType("BLOB");

                    b.Property<int>("ContentSanitizationLevel")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DatePublished")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "datePublished");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "deleted");

                    b.Property<string>("EncryptedContent")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "encryptedContent");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<bool>("SelfDestruct")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "selfDestruct");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "viewCount");

                    b.HasKey("Id");

                    b.HasIndex("Slug");

                    b.HasIndex("UserId");

                    b.ToTable("monographs", (string)null);
                });

            modelBuilder.Entity("Notesnook.API.Models.SyncDevice", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSyncReset")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAccessTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "DeviceId");

                    b.ToTable("sync_devices", (string)null);
                });

            modelBuilder.Entity("Notesnook.API.Models.SyncItem", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "alg");

                    b.Property<string>("Cipher")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cipher");

                    b.Property<long>("DateSynced")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "dateSynced");

                    b.Property<string>("IV")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "iv");

                    b.Property<int?>("KeyVersion")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "keyVersion");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "length");

                    b.Property<double>("Version")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "v");

                    b.HasKey("UserId", "Type", "ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("sync_items", (string)null);
                });

            modelBuilder.Entity("Notesnook.API.Models.UserSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentsKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataEncryptionKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("InboxKeys")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegacyDataEncryptionKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("MonographPasswordsKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
